### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by RE-A** [RE-A/Naver_News_Title-Context_Crawler#2]
- [x] 파이썬 버젼 명시
- [x] 수정
> 함수명에 cleaner같은 명사쓰다가 beautify같은 동사 쓰다가 섞이는데
> 클래스명 같은 오브젝트에만 명사를 주고 함수에는 동사를 주는걸 추천함

------------------------------------------------

- [x] 출력 엑셀에 기사별로 날짜, 분야 열 추가하기

--------------------------------------------------

- [ ] aggresive summary clean ( 사진 위의 단문들을 모두 잘라냄. strong 태그 아닌 것도 잘라낼 수 있지만, 일반적인 기사의 문장도 잘라낼 위험이 있는 공격적인 옵션) 옵션 추가
  * https://news.naver.com/main/ranking/read.nhn?mid=etc&sid1=111&rankingType=popular_day&oid=001&aid=0011057765&date=20190903&type=1&rankingSeq=8&rankingSectionId=101
  * https://news.naver.com/main/ranking/read.nhn?mid=etc&sid1=111&rankingType=popular_day&oid=001&aid=0011057938&date=20190903&type=1&rankingSeq=5&rankingSectionId=102
- [x]  < b > (= < strong >) 태그 제거를 summary clean에 추가.
- [ ] 기사 첫 문장이 단문(20자 이하?)에 . / ? 등등의 완성형 문장이 아닐 경우 자름.. 이과정 반복.
  * https://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=102&oid=001&aid=0011058172
- [ ] copyright, ⓒ , ~~@~~ 가 들어간 부분을 모두 지우는 기능 추가.

---------------------------------------------------------------------

- [ ] 특정 문자들을 replace()의 반복을 통해 지우고 있는데, 효율적으로 지우도록 개선

**Comment by RE-A** [comment]
수정 완료
